# Generated by Django 5.0.4 on 2024-04-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', editable=False, max_length=100, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='projects.person')),
            ],
            options={
                'ordering': ('person', '-expiry'),
                'indexes': [models.Index(fields=['person', '-expiry'], name='users_sessi_person__629f9f_idx'), models.Index(fields=['token'], name='users_sessi_token_1096d4_idx')],
            },
        ),
    ]
