# Generated by Django 3.1.2 on 2021-08-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_trigger', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=40, null=True)),
                ('project', models.ForeignKey(db_column='public_key', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='projects.project')),
            ],
            options={
                'ordering': ('project', 'event_trigger'),
                'unique_together': {('project', 'event_trigger')},
            },
        ),
    ]
