# Generated by Django 5.0.4 on 2024-04-08 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('mfa_code', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'ordering': ('email',),
                'indexes': [models.Index(fields=['-created', 'email'], name='accounts_us_created_9e6b71_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('user', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='reset', to='accounts.user')),
            ],
        ),
    ]
