name: Django (CI Tests)

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   SEND_GRID_KEY: ${{ secrets.SEND_GRID_KEY }}
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
    #   STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
    #   STRIPE_LIGHT_PLAN: ${{ secrets.STRIPE_LIGHT_PLAN }}
    #   STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
    #   SUPPORT_URL: ${{ secrets.SUPPORT_URL }}
    #   SUPPORT_PROJECT_ID: ${{ secrets.SUPPORT_PROJECT_ID }}
    #   SUPPORT_USER_NAME: ${{ secrets.SUPPORT_USER_NAME }}
    #   SUPPORT_USER_SECRET: ${{ secrets.SUPPORT_USER_SECRET }}
    #   WEBSITE_URL: ${{ secrets.WEBSITE_URL }}

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.12]
        redis-version: [6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test --exclude-tag=server_must_run
