name: Docker Build (CI Test)

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build ./api.chatengine.io -t api2.chatengine.io:latest
