name: (CI Tests) api.chatengine.io

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SEND_GRID_KEY: ${{ secrets.SEND_GRID_KEY }}

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api.chatengine.io/requirements.txt
      - name: Run Tests
        working-directory: api.chatengine.io
        run: |
          python manage.py test --exclude-tag=server_must_run
